version: '3.7'

networks:
  mongo_node:

volumes:
  data-db:
    driver: local

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-webserver
    ports:
      - '8080:80'
    volumes:
      - ./code/frontend/build:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express
      - mongo
      - client
    networks:
      - mongo_node

  mongo:
    image: mongo:4.2.5
    container_name: mongo-db
    restart: unless-stopped
    tty: true
    ports:
      - '27017:27017'
    volumes:
      - data-db:/var/lib/mongo
    env_file:
      - ./config/db/.env
    networks:
      - mongo_node

  express:
    build:
      context: ./code/api
      dockerfile: Dockerfile
    container_name: express
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./code/api:/usr/src/app
    environment:
      DB_HOST: mongo-db
      PORT: 9000
      SOCKET_PORT: 9008
    env_file:
      - ./config/server/.env
    ports:
      - '9000:9000'
      - '9008:9008'
    networks:
      - mongo_node

  client:
    build:
      context: ./code/frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm start
    volumes:
      - ./code/frontend:/usr/src/app
    environment:
      - REACT_APP_BASE_URL=http://localhost:9000
      - REACT_APP_SOCKET_PORT=http://localhost:9008
    ports:
      - '3000:3000'
    networks:
      - mongo_node
